@hostname = localhost
@port = 8080
@baseUrl = http://{{hostname}}:{{port}}
@token = your_token_here

POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "test8",
  "password": "password"
}
###
GET https://ya.ru/
Authorization:


